// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA73AWCLBilRFuzsbMliE50DGWcR9zGDg4',
    appId: '1:576916721093:web:6176b28ab5f13ead27cfac',
    messagingSenderId: '576916721093',
    projectId: 'chat-app-flutter-c2fa7',
    authDomain: 'chat-app-flutter-c2fa7.firebaseapp.com',
    storageBucket: 'chat-app-flutter-c2fa7.appspot.com',
    measurementId: 'G-JRL01WD334',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJPgKU3zgeoQ5pww6oKcMfmW-mdrfsMV8',
    appId: '1:576916721093:android:30b6bea49cb84f4027cfac',
    messagingSenderId: '576916721093',
    projectId: 'chat-app-flutter-c2fa7',
    storageBucket: 'chat-app-flutter-c2fa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc2YbKyMpJNwEV8omUAY0ypT24DgAM6u4',
    appId: '1:576916721093:ios:ecd75b8cedcec52927cfac',
    messagingSenderId: '576916721093',
    projectId: 'chat-app-flutter-c2fa7',
    storageBucket: 'chat-app-flutter-c2fa7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc2YbKyMpJNwEV8omUAY0ypT24DgAM6u4',
    appId: '1:576916721093:ios:ecd75b8cedcec52927cfac',
    messagingSenderId: '576916721093',
    projectId: 'chat-app-flutter-c2fa7',
    storageBucket: 'chat-app-flutter-c2fa7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA73AWCLBilRFuzsbMliE50DGWcR9zGDg4',
    appId: '1:576916721093:web:aedf6e528d77184527cfac',
    messagingSenderId: '576916721093',
    projectId: 'chat-app-flutter-c2fa7',
    authDomain: 'chat-app-flutter-c2fa7.firebaseapp.com',
    storageBucket: 'chat-app-flutter-c2fa7.appspot.com',
    measurementId: 'G-6X75B9K9TQ',
  );
}
